# Generated by Django 5.2.4 on 2025-07-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_contenido_articulo_contenido_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='icono',
            field=models.CharField(choices=[('assets/icono1.png', 'Icono 1'), ('assets/icono2.png', 'Icono 2'), ('assets/icono3.png', 'Icono 3')], default='assets/icono1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='lector',
            name='icono',
            field=models.CharField(choices=[('assets/icono1.png', 'Icono 1'), ('assets/icono2.png', 'Icono 2'), ('assets/icono3.png', 'Icono 3')], default='assets/icono1.png', max_length=100),
        ),
    ]
