# Generated by Django 5.2.4 on 2025-07-26 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_autor_icono_lector_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='principal.articulo')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.lector')),
            ],
        ),
    ]
