# Generated by Django 5.2.4 on 2025-07-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
